version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cocopasty-backend/"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "npm"
    directory: "/cocopasty-frontend/"
    schedule:
      interval: "daily"
      day: "friday"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/cocopasty-backend"
    schedule:
      interval: "weekly"
      day: "friday"
  - package-ecosystem: "docker"
    directory: "/cocopasty-frontend"
    schedule:
      interval: "weekly"
      day: "friday"
