services:
  frontend:
    build: ./cocopasty-frontend
    ports:
      - "8080:80"
    environment:
      VUE_APP_BACKEND_PORT: 8081
      VUE_APP_BACKEND_HOST: "http://localhost"
    depends_on:
      - backend
  backend:
    build: ./cocopasty-backend
    ports:
      - "8081:8080"
    environment:
      LOG_LEVEL: "debug"
      REDIS_HOST: "redis:6379"
#     REDIS_PASSWORD: "123" currently not used
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"