services:
  frontend:
    build: ./cocopasty-frontend
    ports:
      - "8080:80"
    environment:
      VUE_APP_BACKEND_PORT: 8081
      VUE_APP_BACKEND_HOST: "http://localhost"
  backend:
    build: ./cocopasty-backend
    ports:
      - "8081:8080"
    environment:
      LOG_LEVEL: debug
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"